### ISSUE TITLE
Making Swift Concurrency work

### ISSUE THREAD

**Issue by lk251** [mironal/TwitterAPIKit#126]
Hi @mironal, I would like to help implement things with Swift Concurrency, which is currently experimental in this repo. What could I do to help? Thank you.

**Comment by mironal** [comment]
Thank you!

TwitterAPIKit tentatively supports Swift Concurrency.
> https://github.com/mironal/TwitterAPIKit#swift-concurrency-experimental

However, I am not that familiar with Swift Concurrency or Swift UI.

It would be very helpful if you could give me some feedback on your experience with TwitterAPIKit.

**Comment by lk251** [comment]
I will! I am learning these things myself. I will be happy to share my experience as soon as I can try TwitterAPIKit, hopefully in the next couple of weeks.
